{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "detector-orchestration.fullname" . }}
  labels:
    {{- include "detector-orchestration.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "detector-orchestration.fullname" . }}
  labels:
    {{- include "detector-orchestration.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "detector-orchestration.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "detector-orchestration.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
