{{- if and .Values.inlineConfigs.enabled .Values.inlineConfigs.detectors }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-mapper.fullname" . }}-detectors
  labels:
    {{- include "llama-mapper.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.inlineConfigs.detectors }}
  {{ $filename }}: |
{{- $content | nindent 4 }}
  {{- end }}
{{- end }}
