{{- if and .Values.inlineConfigs.enabled .Values.inlineConfigs.frameworksYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-mapper.fullname" . }}-frameworks
  labels:
    {{- include "llama-mapper.labels" . | nindent 4 }}
data:
  frameworks.yaml: |
{{- .Values.inlineConfigs.frameworksYaml | nindent 4 }}
{{- end }}
