{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llama-mapper.fullname" . }}
  labels:
    {{- include "llama-mapper.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
