{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llama-mapper.serviceAccountName" . }}
  labels:
    {{- include "llama-mapper.labels" . | nindent 4 }}
{{- end }}
