apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-mapper.fullname" . }}
  labels:
    {{- include "llama-mapper.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llama-mapper.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
